language: node_js
sudo: false
node_js:
  - "4.1"
before_install:
  - cd $TRAVIS_BUILD_DIR/Source_Code
before_script:
  - cd $TRAVIS_BUILD_DIR/Source_Code
install:
  - npm install
script:
  - npm start